### ISSUE TITLE
Legacy LMS_SetSampleRate does not apply the RF oversampling ratio

### ISSUE THREAD

**Issue by davecrump** [myriadrf/LimeSuiteNG#53]
I am using the legacy function LMS_SetSampleRate(device, bandwidth, 4) on a 64-bit bookworm install on a LimeNET Micro 2.0 DE.  

On the old LimeSuite, LMS_GetSampleRate would report an RF sampling rate 4 times higher than the host sample rate.  On LimeSuiteNG they are reported as identical - ie the oversampling ratio is always set at 1.  It appears that the requested oversampling ratio is not being applied.

This means that it is not possible to use host sampling rates below 5 MHz as the RF Sampling rate is limited to a lower limit of 5 MHz without oversampling.  I have observed the behaviour both on TX and RX.

**Comment by rjonaitis** [comment]
The oversampling was being applied, only the readback RF sampling rate value was not being updated.
The lower limit of sampling rate is dictated by interface between FPGA and LMS7002M chip, oversampling is done inside the chip, so oversampling usage will not affect the lower limit of host sampling rate.
