### ISSUE TITLE
Receive stream fails with host sample rates of less than 210000

### ISSUE THREAD

**Issue by davecrump** [myriadrf/LimeSuiteNG#56]
I am using the legacy function LMS_SetSampleRate(device, bandwidth, oversampling) on a 64-bit bookworm install on a LimeNET Micro 2.0 DE to generate a stream that is put into an fft and displayed.  The basic code is the same as a legacy limesuite application that I have been using for 3 years with LimeSDR Mini and LimeSDR USB.  This is related to [https://github.com/myriadrf/LimeSuiteNG/issues/53](url)

The simplifed code that I am using is:
```
printf("Calling LMS_SetSampleRate\n");
return_value = LMS_SetSampleRate(device, bandwidth, 4);
printf("Called LMS_SetSampleRate(device, %1.f, 4) returned %d\n", bandwidth, return_value);      
LMS_GetSampleRate(device, LMS_CH_RX, 0, &sr_host, &sr_rf);
printf("Lime RX Samplerate: Host: %.1fKs, RF: %.1fKs\n", (sr_host/1000.0), (sr_rf/1000.0));

```
The results I get with various parameters are shown here:
```
Calling LMS_SetSampleRate
Called LMS_SetSampleRate(device, 20480000, 4) returned 0
Lime RX Samplerate: Host: 20480.0Ks, RF: 81920.0Ks
```
Actual stream sample rate is 10240000

```
Calling LMS_SetSampleRate
Called LMS_SetSampleRate(device, 10240000, 4) returned 0
Lime RX Samplerate: Host: 10240.0Ks, RF: 40960.0Ks
```
Actual stream sample rate is 5120000

```
Calling LMS_SetSampleRate
CMD 56 Read timeout
Called LMS_SetSampleRate(device, 5120000, 4) returned 0
Lime RX Samplerate: Host: 5120.0Ks, RF: 20480.0Ks
```
Actual stream sample rate is 2560000

```
Calling LMS_SetSampleRate
CMD 56 Read timeout
CMD 55 Read timeout
FPGA SetPllClock: failed to write registers
Called LMS_SetSampleRate(device, 3000000, 4) returned 0
Lime RX Samplerate: Host: 3000.0Ks, RF: 12000.0Ks
```
Actual stream sample rate is 1500000

```
Calling LMS_SetSampleRate
FPGA SetPllFrequency: PLL[1] input frequency must be >=5 MHz
Called LMS_SetSampleRate(device, 2100000, 4) returned 0
Lime RX Samplerate: Host: 2100.0Ks, RF: 8400.0Ks

```
Actual stream sample rate is 1050000

```
Calling LMS_SetSampleRate
FPGA SetPllFrequency: PLL[1] input frequency must be >=5 MHz
Called LMS_SetSampleRate(device, 2048000, 4) returned 0
Lime RX Samplerate: Host: 2048.0Ks, RF: 8192.0Ks
No samples or timeout
No samples or timeout
No samples or timeout
```

```
Calling LMS_SetSampleRate
FPGA SetPllFrequency: PLL[1] input frequency must be >=5 MHz
Called LMS_SetSampleRate(device, 512000, 8) returned 0
Lime RX Samplerate: Host: 512.0Ks, RF: 4096.0Ks
No samples or timeout
No samples or timeout
No samples or timeout
```

In all cases where it actually produces a stream, the sample rate is half of what is requested.  Before commit d09e94c, the sample rate was correct on initial startup, but if changed would go to half rate. 

Using Legacy LimeSuite, I can go down as far as:

```
Calling LMS_SetSampleRate
Called LMS_SetSampleRate(device, 102400, 32) returned 0
Lime RX Samplerate: Host: 102.4Ks, RF: 3276.8Ks
```
and the same code produces the correct sample rate.

**Comment by rjonaitis** [comment]
Fixed the halving of sample rate after repeated stream starts using the legacy API wrapper 5f496aee31775d8bab265b8177a90ee4551a5ace
