### ISSUE TITLE
Legacy LMS API function LMS_SetNormalizedGain has incorrect gain scaling

### ISSUE THREAD

**Issue by davecrump** [myriadrf/LimeSuiteNG#84]
I am using the legacy function LMS_SetNormalizedGain(device, LMS_CH_TX, channel, gain) on a 64-bit bookworm lite install on a LimeNET Micro 2.0 DE.  LimeSuiteNG commit [7072fe9](https://github.com/myriadrf/LimeSuiteNG/commit/7072fe9f7bf1c347bc8730bc6d142927c2b7b500) , LimeSDR XTRX Library 0.1.0-g7072fe9f Firmware 4 Gateware 1.15.

The transmit gain scaling on LMS_SetNormalizedGain on the old LimeSuite is scaled from 0.0 to 1.0.  When using the LimeSuiteNG legacy API on a LimeXTRX it seems to be scaled from 0.0 to 0.60.  Example results (gain, relative output):

0.10, -40dB
0.20, -38db
0.30, -22dB
0.40, -22dB
0.50, -15dB
0.60, -9dB
0.70, -10dB
0.80, -9dB
0.84, -9dB
0.85, -40dB
0.90, -40dB

Note the plateau at 0.60 and the discontinuity at 0.85.  For reference -9dB equated to about 19dBm of power output at 437 MHz, so about what I would expect as the maximum from the LimeNET Micro 2.0 DE.

Edit: I have just checked and the erroneous behaviour is similar when using LimeSuiteNG with a LimeSDR Mini V2. 

At all gain settings, the output on the LimeSDR XTRX appeared to be suffering from signal compression.  I will raise a separate issue #85 about that.

Dave

**Comment by rjonaitis** [comment]
https://github.com/myriadrf/LimeSuiteNG/commit/8ec583ccedb4e81b963bb70fa70ecdbc7704bf07 combined with https://github.com/myriadrf/LimeSuiteNG/commit/f8bbdabc344e50b347166dc491d97fe511ceabeb fixed this issue.

**Comment by davecrump** [comment]
Using [23b0a90](https://github.com/myriadrf/LimeSuiteNG/commit/23b0a90970c0be9b60e8eb5d2136ff3db52eda23) the behaviour is now as would be expected on a LimeSDR Mini.

However on the LimeNET Micro DE it is still not right.  Output is constant for any setting above 0.60, and reduces for settings below that.

Dave
